[phases.setup]
nixPkgs = ["nodejs_20", "python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["pip install -U yt-dlp --quiet", "npm run build"]

[start]
cmd = "npm start"
